// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtbqbneaaccpnxowvfud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0YnFibmVhYWNjcG54b3d2ZnVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0ODk1NTMsImV4cCI6MjA3MjA2NTU1M30.OIGMaFWvXJRco3u4-lPyM863jRf1oEHqdG21Rvt3r9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});